Repository BioJulia/biojulia.github.io, pull requests merged in 2023-08, with the labels that each got.

#17 Fix badges
  _css/franklin.css
  _layout/header.html
Labels: Styling

#21 Add old blog posts
  _assets/posts/automa1/automa_tutorial_13_0.svg
  _assets/posts/automa1/automa_tutorial_25_0.svg
  _assets/posts/automa1/automa_tutorial_2_0.svg
  _assets/posts/automa1/automa_tutorial_37_0.svg
  _assets/posts/automa1/automa_tutorial_47_0.svg
  _assets/posts/automa1/automa_tutorial_4_0.svg
  _assets/posts/automa1/automa_tutorial_6_0.svg
  _assets/posts/biojl/featured.png
  _assets/posts/biojl/featured_hu673fdf9bf6c03bbd2130cc0e6402b2ac_100218_150x0_resize_lanczos_2.png
  _assets/posts/biojl/featured_hu673fdf9bf6c03bbd2130cc0e6402b2ac_100218_720x0_resize_lanczos_2.png
  _assets/posts/hardware/pluto.html
  _assets/posts/seq-lang/featured.png
  _assets/posts/seq-lang/featured_hu673fdf9bf6c03bbd2130cc0e6402b2ac_100218_150x0_resize_lanczos_2.png
  _assets/posts/seq-lang/featured_hu673fdf9bf6c03bbd2130cc0e6402b2ac_100218_720x0_resize_lanczos_2.png
  _assets/posts/seq-lang/fig1.png
  _assets/posts/seq-lang/fig2.png
  _assets/posts/seq-lang/fig3-a.png
  _assets/posts/seq-lang/fig3-b.png
  _assets/posts/seq-lang/fig3-c.png
  _assets/posts/seq-lang/fig3.png
  _assets/posts/seq-lang/fig4.png
  _assets/posts/seq-lang/fig5.png
  _assets/scripts/hardware.jl
  _layout/header.html
  posts/automa1.md
  posts/biojl.md
  posts/hardware.md
  posts/index.md
  posts/seq-lang.md
Labels: Content

#20 Add join page
  .github/workflows/Deploy.yml
  _layout/header.html
  index.md
  join.md
Labels: enhancement, Content
